// Legacy native/Pi builder; GitHub Pages does not use this server.
import express from 'express';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import {randomUUID} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {mkdtemp, mkdir, rm, writeFile, copyFile, stat, readdir, unlink, readFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {extensionBlocks} from './src/blocks/block-catalog.js';

const app = express();
const port = Number.parseInt(process.env.PORT ?? '4173', 10);
const host = process.env.HOST ?? '0.0.0.0';
const production = process.argv.includes('--production');
const currentFile = fileURLToPath(import.meta.url);
const currentDirectory = path.dirname(currentFile);
const distributionDirectory = path.join(currentDirectory, 'dist');
const kernelDirectory = path.join(currentDirectory, 'kernel');
const assetsDirectory = path.join(currentDirectory, 'project-assets');
const serverImportsDirectory = path.join(currentDirectory, 'server-imports');
const MAX_SOURCE_BYTES = 500_000;
const MAX_PROCESS_OUTPUT = 750_000;
const MAX_INPUT_BYTES = 8_192;
const QEMU_SESSION_MS = Number.parseInt(process.env.BLOCKOS_QEMU_TIMEOUT_MS ?? '120000', 10);
const sessions = new Map();

await mkdir(assetsDirectory, {recursive: true});
await mkdir(serverImportsDirectory, {recursive: true});

app.disable('x-powered-by');
app.use(express.json({limit: '128mb'}));
app.use('/novnc', express.static('/usr/share/novnc', {maxAge: '1h'}));


function extractFunctionSource(source, symbol) {
  let searchFrom = 0;
  while (searchFrom < source.length) {
    const symbolIndex = source.indexOf(symbol, searchFrom);
    if (symbolIndex < 0) return null;

    const before = source[symbolIndex - 1] ?? '';
    const after = source[symbolIndex + symbol.length] ?? '';
    if ((before && /[A-Za-z0-9_]/.test(before)) || (after && /[A-Za-z0-9_]/.test(after))) {
      searchFrom = symbolIndex + symbol.length;
      continue;
    }

    const openParen = source.indexOf('(', symbolIndex + symbol.length);
    if (openParen < 0) return null;

    let parenDepth = 0;
    let closeParen = -1;
    for (let index = openParen; index < source.length; index += 1) {
      if (source[index] === '(') parenDepth += 1;
      if (source[index] === ')') {
        parenDepth -= 1;
        if (parenDepth === 0) {
          closeParen = index;
          break;
        }
      }
    }
    if (closeParen < 0) return null;

    let braceStart = closeParen + 1;
    while (/\s/.test(source[braceStart] ?? '')) braceStart += 1;
    if (source[braceStart] !== '{') {
      searchFrom = symbolIndex + symbol.length;
      continue;
    }

    let start = source.lastIndexOf('\n', symbolIndex);
    start = start < 0 ? 0 : start + 1;
    let braceDepth = 0;
    let inString = false;
    let quote = '';
    let escaped = false;

    for (let index = braceStart; index < source.length; index += 1) {
      const value = source[index];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (value === '\\') {
          escaped = true;
        } else if (value === quote) {
          inString = false;
        }
        continue;
      }

      if (value === '"' || value === "'") {
        inString = true;
        quote = value;
        continue;
      }

      if (value === '{') braceDepth += 1;
      if (value === '}') {
        braceDepth -= 1;
        if (braceDepth === 0) return source.slice(start, index + 1).trim();
      }
    }
    return null;
  }
  return null;
}

async function findLearningSource(symbol) {
  const candidates = [
    {file: 'kernel/extensions_runtime.c', path: path.join(kernelDirectory, 'extensions_runtime.c')},
    {file: 'kernel/runtime.c', path: path.join(kernelDirectory, 'runtime.c')},
  ];
  for (const candidate of candidates) {
    const source = await readFile(candidate.path, 'utf8');
    const functionSource = extractFunctionSource(source, symbol);
    if (functionSource) return {file: candidate.file, source: functionSource};
  }
  return null;
}

function safeFileName(value) {
  const base = path.basename(String(value || 'asset.bin'));
  const cleaned = base.replace(/[^A-Za-z0-9._-]/g, '_').replace(/_+/g, '_');
  return cleaned.slice(0, 120) || 'asset.bin';
}

function validateGeneratedSource(code) {
  if (typeof code !== 'string') return 'The request did not contain C source code.';
  if (Buffer.byteLength(code, 'utf8') > MAX_SOURCE_BYTES) return 'The generated source is too large.';
  if (!code.startsWith('// Generated by BlockOS Studio.')) return 'Only code generated by BlockOS Studio can be built here.';
  if (!/\bvoid\s+kernel_main\s*\(\s*void\s*\)/.test(code)) return 'The generated source has no kernel_main(void) entry point.';
  const directives = code.match(/^\s*#.*$/gm) ?? [];
  const allowed = new Set(['#include <stdbool.h>', '#include <stddef.h>', '#include <stdint.h>']);
  for (const directive of directives) {
    if (!allowed.has(directive.trim())) return `Unsupported preprocessor directive: ${directive.trim()}`;
  }
  return null;
}

function runProcess(command, args, options = {}) {
  const timeoutMs = options.timeoutMs ?? 30_000;
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      env: {...process.env, ...(options.env ?? {})},
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    let finished = false;
    let timedOut = false;
    const append = (current, chunk) => (current + chunk.toString('utf8')).slice(0, MAX_PROCESS_OUTPUT);
    child.stdout.on('data', (chunk) => { stdout = append(stdout, chunk); });
    child.stderr.on('data', (chunk) => { stderr = append(stderr, chunk); });
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill('SIGTERM');
      setTimeout(() => child.kill('SIGKILL'), 500).unref();
    }, timeoutMs);
    child.on('error', (error) => {
      if (finished) return;
      finished = true;
      clearTimeout(timer);
      resolve({ok: false, code: null, signal: null, stdout, stderr: `${stderr}${error.message}\n`, timedOut});
    });
    child.on('close', (code, signal) => {
      if (finished) return;
      finished = true;
      clearTimeout(timer);
      resolve({ok: code === 0 || timedOut, code, signal, stdout, stderr, timedOut});
    });
  });
}

async function commandExists(command) {
  const result = await runProcess('sh', ['-lc', `command -v ${command}`], {timeoutMs: 2500});
  return result.code === 0;
}

const compileFlags = [
  '--target=x86_64-unknown-none-elf',
  '-m64',
  '-mcmodel=kernel',
  '-mno-red-zone',
  '-mno-mmx',
  '-mno-sse',
  '-mno-sse2',
  '-ffreestanding',
  '-fno-stack-protector',
  '-fno-pic',
  '-fno-pie',
  '-fno-builtin',
  '-fno-asynchronous-unwind-tables',
  '-fno-unwind-tables',
  '-nostdinc',
  '-Wall',
  '-Wextra',
  '-Werror=implicit-function-declaration',
];

async function listAssets() {
  const entries = await readdir(assetsDirectory, {withFileTypes: true});
  const output = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const info = await stat(path.join(assetsDirectory, entry.name));
    output.push({name: entry.name, bytes: info.size});
  }
  return output.sort((a, b) => a.name.localeCompare(b.name));
}

async function buildKernel(code) {
  const sourceError = validateGeneratedSource(code);
  if (sourceError) return {ok: false, stage: 'validation', output: sourceError};
  const required = ['clang', 'ld.lld', 'grub-mkrescue'];
  const missing = [];
  for (const tool of required) if (!(await commandExists(tool))) missing.push(tool);
  if (missing.length) return {ok: false, stage: 'tools', output: `Missing build tools: ${missing.join(', ')}.`};

  const work = await mkdtemp(path.join(os.tmpdir(), 'blockos-x64-build-'));
  try {
    const includeDirectory = path.join(work, 'include');
    await mkdir(includeDirectory);
    for (const header of ['stdint.h', 'stddef.h', 'stdbool.h']) {
      await copyFile(path.join(kernelDirectory, 'include', header), path.join(includeDirectory, header));
    }
    for (const file of ['boot.S', 'runtime.c', 'extensions_runtime.c', 'linker.ld']) {
      await copyFile(path.join(kernelDirectory, file), path.join(work, file));
    }
    await writeFile(path.join(work, 'kernel.c'), code, 'utf8');

    const compileUnits = [['boot.S', 'boot.o'], ['runtime.c', 'runtime.o'], ['extensions_runtime.c', 'extensions.o'], ['kernel.c', 'kernel.o']];
    const buildLog = [];
    for (const [source, object] of compileUnits) {
      const result = await runProcess('clang', [...compileFlags, '-I', includeDirectory, '-c', source, '-o', object], {cwd: work});
      buildLog.push(`$ clang x86_64 -c ${source}\n${result.stdout}${result.stderr}`.trim());
      if (result.code !== 0) return {ok: false, stage: 'compile', output: buildLog.join('\n\n'), work};
    }

    const link = await runProcess('ld.lld', ['-m', 'elf_x86_64', '-nostdlib', '-T', 'linker.ld', '-o', 'blockos.elf', 'boot.o', 'runtime.o', 'extensions.o', 'kernel.o'], {cwd: work});
    buildLog.push(`$ ld.lld -m elf_x86_64 blockos.elf\n${link.stdout}${link.stderr}`.trim());
    if (link.code !== 0) return {ok: false, stage: 'link', output: buildLog.join('\n\n'), work};

    const isoRoot = path.join(work, 'iso');
    const isoBoot = path.join(isoRoot, 'boot');
    const isoGrub = path.join(isoBoot, 'grub');
    const isoAssets = path.join(isoRoot, 'assets');
    await mkdir(isoGrub, {recursive: true});
    await mkdir(isoAssets, {recursive: true});
    await copyFile(path.join(work, 'blockos.elf'), path.join(isoBoot, 'blockos.elf'));

    const assets = await listAssets();
    const moduleLines = [];
    for (const asset of assets) {
      await copyFile(path.join(assetsDirectory, asset.name), path.join(isoAssets, asset.name));
      moduleLines.push(`    module2 /assets/${asset.name} ${asset.name}`);
    }
    const grubConfig = `set timeout=0\nset default=0\n\nmenuentry "BlockOS x86_64" {\n    set gfxmode=1024x768x32\n    set gfxpayload=keep\n    multiboot2 /boot/blockos.elf\n${moduleLines.join('\n')}\n    boot\n}\n`;
    await writeFile(path.join(isoGrub, 'grub.cfg'), grubConfig, 'utf8');

    const iso = await runProcess('grub-mkrescue', ['-o', 'blockos-x86_64.iso', 'iso'], {cwd: work, timeoutMs: 60_000});
    buildLog.push(`$ grub-mkrescue blockos-x86_64.iso\n${iso.stdout}${iso.stderr}`.trim());
    if (iso.code !== 0) return {ok: false, stage: 'iso', output: buildLog.join('\n\n'), work};

    const kernelInfo = await stat(path.join(work, 'blockos.elf'));
    const isoInfo = await stat(path.join(work, 'blockos-x86_64.iso'));
    return {ok: true, work, kernelBytes: kernelInfo.size, isoBytes: isoInfo.size, buildOutput: buildLog.join('\n\n'), assetCount: assets.length};
  } catch (error) {
    await rm(work, {recursive: true, force: true});
    return {ok: false, stage: 'server', output: error instanceof Error ? error.message : String(error)};
  }
}

function appendSessionOutput(session, chunk) {
  session.output = (session.output + chunk.toString('utf8')).slice(0, MAX_PROCESS_OUTPUT);
  session.updatedAt = Date.now();
}

function stopSession(session, reason = 'stopped') {
  if (!session || !session.running) return;
  session.stopReason = reason;
  session.child.kill('SIGTERM');
  if (session.websockifyChild) session.websockifyChild.kill('SIGTERM');
  setTimeout(() => {
    if (session.running) session.child.kill('SIGKILL');
    if (session.websockifyChild && !session.websockifyChild.killed) session.websockifyChild.kill('SIGKILL');
  }, 700).unref();
}

async function findVncDisplay() {
  for (let display = 1; display < 100; display += 1) {
    const available = await new Promise((resolve) => {
      const tester = net.createServer();
      tester.once('error', () => resolve(false));
      tester.listen(5900 + display, '127.0.0.1', () => tester.close(() => resolve(true)));
    });
    if (available) return display;
  }
  throw new Error('No free local VNC port was found.');
}

async function findPublicWebSocketPort() {
  for (let candidate = 6080; candidate <= 6099; candidate += 1) {
    const available = await new Promise((resolve) => {
      const tester = net.createServer();
      tester.once('error', () => resolve(false));
      tester.listen(candidate, '0.0.0.0', () => tester.close(() => resolve(true)));
    });
    if (available) return candidate;
  }
  throw new Error('No free display WebSocket port was found between 6080 and 6099.');
}

async function startQemuSession(build) {
  const display = await findVncDisplay();
  const id = randomUUID();
  const websockifyPort = await findPublicWebSocketPort();
  const child = spawn('qemu-system-x86_64', [
    '-machine', 'pc,accel=tcg',
    '-cpu', 'qemu64',
    '-m', '256M',
    '-cdrom', 'blockos-x86_64.iso',
    '-boot', 'd',
    '-vnc', `127.0.0.1:${display}`,
    '-chardev', 'stdio,id=blockos_serial,signal=off',
    '-serial', 'chardev:blockos_serial',
    '-monitor', 'none',
    '-no-reboot',
    '-no-shutdown',
  ], {cwd: build.work, env: process.env, stdio: ['pipe', 'pipe', 'pipe']});

  const websockifyChild = spawn('websockify', [String(websockifyPort), `127.0.0.1:${5900 + display}`], {
    cwd: build.work, env: process.env, stdio: ['ignore', 'pipe', 'pipe'],
  });

  const session = {
    id, child, websockifyChild, websockifyPort, work: build.work, kernelBytes: build.kernelBytes, isoBytes: build.isoBytes,
    buildOutput: build.buildOutput, assetCount: build.assetCount, vncPort: 5900 + display,
    output: '', running: true, exitCode: null, signal: null, stopReason: null,
    createdAt: Date.now(), updatedAt: Date.now(),
  };
  sessions.set(id, session);
  websockifyChild.stdout.on('data', (chunk) => appendSessionOutput(session, `[websockify] ${chunk}`));
  websockifyChild.stderr.on('data', (chunk) => appendSessionOutput(session, `[websockify] ${chunk}`));
  child.stdout.on('data', (chunk) => appendSessionOutput(session, chunk));
  child.stderr.on('data', (chunk) => appendSessionOutput(session, chunk));
  child.on('error', (error) => appendSessionOutput(session, `\n[QEMU error] ${error.message}\n`));
  child.on('close', async (code, signal) => {
    session.running = false;
    session.exitCode = code;
    session.signal = signal;
    session.updatedAt = Date.now();
    clearTimeout(session.timeout);
    await rm(build.work, {recursive: true, force: true});
    setTimeout(() => sessions.delete(id), 10 * 60 * 1000).unref();
  });
  session.timeout = setTimeout(() => stopSession(session, 'time limit'), QEMU_SESSION_MS);
  return session;
}

function publicSession(session) {
  return {
    ok: true, sessionId: session.id, running: session.running, kernelBytes: session.kernelBytes,
    isoBytes: session.isoBytes, assetCount: session.assetCount, output: session.output,
    exitCode: session.exitCode, signal: session.signal, stopReason: session.stopReason,
    elapsedMs: Date.now() - session.createdAt, vncReady: session.running, websockifyPort: session.websockifyPort,
  };
}

app.get('/health', async (_request, response) => {
  const tools = {};
  for (const tool of ['clang', 'ld.lld', 'grub-mkrescue', 'qemu-system-x86_64', 'websockify']) tools[tool] = await commandExists(tool);
  response.json({ok: true, app: 'BlockOS Studio', version: '0.7.0', architecture: 'x86_64', blocks: extensionBlocks.length, sessions: sessions.size, tools});
});


app.get('/api/learning/source', async (request, response) => {
  const symbol = String(request.query?.symbol ?? '');
  if (!/^[A-Za-z_][A-Za-z0-9_]{0,127}$/.test(symbol)) {
    return response.status(400).json({ok: false, output: 'Invalid C symbol name.'});
  }

  try {
    const result = await findLearningSource(symbol);
    if (!result) {
      return response.status(404).json({
        ok: false,
        output: 'This block is generated inline or its runtime function could not be found.',
      });
    }
    response.json({ok: true, symbol, ...result});
  } catch (error) {
    response.status(500).json({ok: false, output: error instanceof Error ? error.message : String(error)});
  }
});

app.get('/api/assets', async (_request, response) => response.json({ok: true, assets: await listAssets()}));

app.post('/api/assets/upload', async (request, response) => {
  const files = Array.isArray(request.body?.files) ? request.body.files : [];
  if (files.length > 32) return response.status(413).json({ok: false, output: 'Upload at most 32 files at once.'});
  const saved = [];
  for (const item of files) {
    const name = safeFileName(item?.name);
    const data = Buffer.from(String(item?.dataBase64 ?? ''), 'base64');
    if (data.length > 32 * 1024 * 1024) return response.status(413).json({ok: false, output: `${name} is larger than 32 MiB.`});
    await writeFile(path.join(assetsDirectory, name), data);
    saved.push(name);
  }
  response.json({ok: true, saved, assets: await listAssets()});
});

app.post('/api/assets/import-server', async (_request, response) => {
  const entries = await readdir(serverImportsDirectory, {withFileTypes: true});
  const imported = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    const name = safeFileName(entry.name);
    await copyFile(path.join(serverImportsDirectory, entry.name), path.join(assetsDirectory, name));
    imported.push(name);
  }
  response.json({ok: true, imported, assets: await listAssets(), folder: serverImportsDirectory});
});

app.delete('/api/assets/:name', async (request, response) => {
  const name = safeFileName(request.params.name);
  await unlink(path.join(assetsDirectory, name)).catch(() => {});
  response.json({ok: true, assets: await listAssets()});
});

app.post('/api/build-run', async (request, response) => {
  if (!(await commandExists('qemu-system-x86_64')) || !(await commandExists('websockify'))) {
    response.status(503).json({ok: false, stage: 'tools', output: 'Missing qemu-system-x86_64 or websockify.'});
    return;
  }
  for (const existing of sessions.values()) if (existing.running) stopSession(existing, 'replaced by a new run');
  const build = await buildKernel(request.body?.code);
  if (!build.ok) {
    if (build.work) await rm(build.work, {recursive: true, force: true});
    response.status(build.stage === 'validation' ? 400 : 422).json(build);
    return;
  }
  try {
    const session = await startQemuSession(build);
    response.json({
      ok: true, stage: 'run', sessionId: session.id, running: true,
      kernelBytes: session.kernelBytes, isoBytes: session.isoBytes, assetCount: session.assetCount, websockifyPort: session.websockifyPort,
      buildOutput: session.buildOutput,
      output: `Built a bootable x86_64 ISO (${session.isoBytes} bytes) and started QEMU with a 1024×768 display.`,
    });
  } catch (error) {
    await rm(build.work, {recursive: true, force: true});
    response.status(500).json({ok: false, stage: 'qemu', output: error instanceof Error ? error.message : String(error)});
  }
});

app.post('/api/export-iso', async (request, response) => {
  const build = await buildKernel(request.body?.code);
  if (!build.ok) {
    if (build.work) await rm(build.work, {recursive: true, force: true});
    response.status(build.stage === 'validation' ? 400 : 422).json(build);
    return;
  }
  const isoPath = path.join(build.work, 'blockos-x86_64.iso');
  response.download(isoPath, 'blockos-x86_64.iso', async () => {
    await rm(build.work, {recursive: true, force: true});
  });
});

app.get('/api/run-session/:id', (request, response) => {
  const session = sessions.get(request.params.id);
  if (!session) return response.status(404).json({ok: false, output: 'That QEMU session no longer exists.'});
  response.json(publicSession(session));
});

app.post('/api/run-session/:id/input', (request, response) => {
  const session = sessions.get(request.params.id);
  if (!session) return response.status(404).json({ok: false, output: 'That QEMU session no longer exists.'});
  if (!session.running || !session.child.stdin.writable) return response.status(409).json({ok: false, output: 'QEMU is no longer running.'});
  const input = String(request.body?.input ?? '');
  if (Buffer.byteLength(input, 'utf8') > MAX_INPUT_BYTES) return response.status(413).json({ok: false, output: 'Input is too large.'});
  session.child.stdin.write(input);
  response.json({ok: true, bytes: Buffer.byteLength(input, 'utf8')});
});

app.post('/api/run-session/:id/stop', (request, response) => {
  const session = sessions.get(request.params.id);
  if (!session) return response.status(404).json({ok: false, output: 'That QEMU session no longer exists.'});
  stopSession(session, 'stopped by user');
  response.json({ok: true});
});

if (production) {
  app.use(express.static(distributionDirectory, {extensions: ['html'], maxAge: '1h'}));
  app.use((_request, response) => response.sendFile(path.join(distributionDirectory, 'index.html')));
} else {
  const {createServer: createViteServer} = await import('vite');
  const vite = await createViteServer({root: currentDirectory, server: {middlewareMode: true, host}, appType: 'spa'});
  app.use(vite.middlewares);
}

const httpServer = app.listen(port, host, () => {
  console.log(`BlockOS Studio v0.7 x86_64 is running at http://localhost:${port}`);
});

function shutdown() {
  for (const session of sessions.values()) stopSession(session, 'server shutdown');
  httpServer.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 1500).unref();
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
