import * as Blockly from 'blockly/core';
import {cGenerator} from '../generator/c-generator.js';

const EVENT_COLOUR = 275;
const FLOW_COLOUR = 120;

Blockly.defineBlocksWithJsonArray([
  {
    type: 'os_wait_until',
    message0: 'wait until %1',
    args0: [{type: 'input_value', name: 'CONDITION', check: 'Boolean'}],
    previousStatement: null,
    nextStatement: null,
    colour: FLOW_COLOUR,
    tooltip: 'Pause this task until the condition becomes true. The CPU sleeps between checks.',
    helpUrl: '',
  },
  {
    type: 'os_when_interrupt',
    message0: 'when CPU interrupt wakes %1',
    args0: [{type: 'input_statement', name: 'BODY'}],
    colour: EVENT_COLOUR,
    tooltip: 'Runs after the CPU wakes from an interrupt. This is a cooperative background event.',
    helpUrl: '',
  },
  {
    type: 'os_when_timer_tick',
    message0: 'when timer reaches every %1 ticks %2',
    args0: [
      {type: 'input_value', name: 'INTERVAL', check: 'Number'},
      {type: 'input_statement', name: 'BODY'},
    ],
    colour: EVENT_COLOUR,
    tooltip: 'Runs repeatedly after the chosen number of scheduler wake-up ticks.',
    helpUrl: '',
  },
  {
    type: 'os_when_input_line',
    message0: 'when command line received %1',
    args0: [{type: 'input_statement', name: 'BODY'}],
    colour: EVENT_COLOUR,
    tooltip: 'Runs whenever a complete serial command line is available.',
    helpUrl: '',
  },
  {
    type: 'os_when_condition',
    message0: 'when %1 becomes true %2',
    args0: [
      {type: 'input_value', name: 'CONDITION', check: 'Boolean'},
      {type: 'input_statement', name: 'BODY'},
    ],
    colour: EVENT_COLOUR,
    tooltip: 'Runs once on each false-to-true change of the condition.',
    helpUrl: '',
  },
]);

function valueOr(generator, block, inputName, fallback) {
  return generator.valueToCode(block, inputName, generator.ORDER_NONE) || fallback;
}

function safeId(block) {
  return String(block.id || 'event').replace(/[^A-Za-z0-9_]/g, '_').slice(0, 24);
}

const originalInit = cGenerator.init.bind(cGenerator);
cGenerator.init = function initWithEvents(workspace) {
  originalInit(workspace);
  this.blockOsEvents_ = [];
};

cGenerator.forBlock.os_wait_until = function waitUntil(block, generator) {
  const condition = valueOr(generator, block, 'CONDITION', 'false');
  return `while (!(${condition})) {\n${generator.INDENT}cpu_wait_for_interrupt();\n}\n`;
};

cGenerator.forBlock.os_when_interrupt = function whenInterrupt(block, generator) {
  const id = safeId(block);
  const name = `blockos_event_interrupt_${id}`;
  const body = generator.statementToCode(block, 'BODY') || `${generator.INDENT}// No interrupt event blocks yet.\n`;
  generator.definitions_[name] = `static void ${name}(void) {\n${body}}`;
  generator.blockOsEvents_.push({kind: 'interrupt', name});
  return '';
};

cGenerator.forBlock.os_when_timer_tick = function whenTimerTick(block, generator) {
  const id = safeId(block);
  const name = `blockos_event_timer_${id}`;
  const counter = `blockos_timer_counter_${id}`;
  const interval = valueOr(generator, block, 'INTERVAL', '1');
  const body = generator.statementToCode(block, 'BODY') || `${generator.INDENT}// No timer event blocks yet.\n`;
  generator.definitions_[name] = `static void ${name}(void) {\n${body}}`;
  generator.definitions_[counter] = `static uint64_t ${counter} = 0;`;
  generator.blockOsEvents_.push({kind: 'timer', name, counter, interval});
  return '';
};

cGenerator.forBlock.os_when_input_line = function whenInputLine(block, generator) {
  const id = safeId(block);
  const name = `blockos_event_input_${id}`;
  const body = generator.statementToCode(block, 'BODY') || `${generator.INDENT}// No input event blocks yet.\n`;
  generator.definitions_[name] = `static void ${name}(void) {\n${body}}`;
  generator.blockOsEvents_.push({kind: 'input', name});
  return '';
};

cGenerator.forBlock.os_when_condition = function whenCondition(block, generator) {
  const id = safeId(block);
  const name = `blockos_event_condition_${id}`;
  const state = `blockos_condition_state_${id}`;
  const condition = valueOr(generator, block, 'CONDITION', 'false');
  const body = generator.statementToCode(block, 'BODY') || `${generator.INDENT}// No condition event blocks yet.\n`;
  generator.definitions_[name] = `static void ${name}(void) {\n${body}}`;
  generator.definitions_[state] = `static bool ${state} = false;`;
  generator.blockOsEvents_.push({kind: 'condition', name, state, condition});
  return '';
};

const originalFinish = cGenerator.finish.bind(cGenerator);
cGenerator.finish = function finishWithEvents(code) {
  const events = [...(this.blockOsEvents_ || [])];
  let output = originalFinish(code);
  if (!events.length) return output;

  const dispatch = [];
  dispatch.push('    // Cooperative event dispatcher generated by BlockOS Studio.');
  dispatch.push('    for (;;) {');
  dispatch.push('        cpu_wait_for_interrupt();');

  for (const event of events) {
    if (event.kind === 'interrupt') {
      dispatch.push(`        ${event.name}();`);
    } else if (event.kind === 'input') {
      dispatch.push(`        if (blockos_console_line_available()) ${event.name}();`);
    } else if (event.kind === 'timer') {
      dispatch.push(`        if (++${event.counter} >= (uint64_t)(${event.interval})) {`);
      dispatch.push(`            ${event.counter} = 0;`);
      dispatch.push(`            ${event.name}();`);
      dispatch.push('        }');
    } else if (event.kind === 'condition') {
      dispatch.push(`        bool blockos_now_${event.state} = (bool)(${event.condition});`);
      dispatch.push(`        if (blockos_now_${event.state} && !${event.state}) ${event.name}();`);
      dispatch.push(`        ${event.state} = blockos_now_${event.state};`);
    }
  }
  dispatch.push('    }');

  const kernelPattern = /void kernel_main\(void\) \{([\s\S]*?)\n\}\s*$/;
  if (kernelPattern.test(output)) {
    output = output.replace(kernelPattern, (_match, body) => `void kernel_main(void) {${body}\n${dispatch.join('\n')}\n}\n`);
  } else {
    output += `\nvoid kernel_main(void) {\n${dispatch.join('\n')}\n}\n`;
  }
  return output;
};
