let emulator=null;let loaderPromise=null;let serialText='';
function assetUrl(path){return new URL(path,document.baseURI).href;}
function loadScript(url){return new Promise((resolve,reject)=>{const old=document.querySelector(`script[data-v86-loader="${url}"]`);if(old){if(window.V86)resolve();else old.addEventListener('load',resolve,{once:true});return;}const s=document.createElement('script');s.src=url;s.async=true;s.dataset.v86Loader=url;s.addEventListener('load',resolve,{once:true});s.addEventListener('error',()=>reject(new Error(`Could not load ${url}`)),{once:true});document.head.append(s);});}
async function ensureV86(){if(window.V86)return window.V86;loaderPromise??=loadScript(assetUrl('v86/libv86.js'));await loaderPromise;if(!window.V86)throw new Error('v86 loaded without exposing window.V86.');return window.V86;}
function prepareScreen(c){c.replaceChildren();const text=document.createElement('div');text.style.whiteSpace='pre';text.style.font='14px monospace';text.style.lineHeight='14px';const canvas=document.createElement('canvas');canvas.style.display='none';c.append(text,canvas);}
function imageOption(name,source){const image=typeof source==='string'?{url:source}:{buffer:source};const lower=name.toLowerCase();if(lower.endsWith('.iso'))return{cdrom:image};if(lower.endsWith('.elf')||lower.endsWith('.mb')||lower.endsWith('.multiboot'))return{multiboot:image};if((lower.endsWith('.img')||lower.endsWith('.bin'))&&typeof source!=='string'&&source.byteLength<=2097152)return{fda:image};if(lower.includes('floppy'))return{fda:image};return{hda:image};}
export async function bootBrowserVm({file=null,demoUrl='',screenContainer,onStatus,onSerial}){await stopBrowserVm();const V86=await ensureV86();prepareScreen(screenContainer);serialText='';const name=file?.name||demoUrl.split('/').at(-1)||'boot.img';const source=file?await file.arrayBuffer():assetUrl(demoUrl);emulator=new V86({wasm_path:assetUrl('v86/v86.wasm'),memory_size:134217728,vga_memory_size:16777216,screen_container:screenContainer,bios:{url:assetUrl('v86/seabios.bin')},vga_bios:{url:assetUrl('v86/vgabios.bin')},autostart:true,disable_speaker:false,...imageOption(name,source)});emulator.add_listener('download-progress',e=>{if(e?.lengthComputable&&e.total)onStatus?.(`Loading ${e.file_name||name} · ${Math.round(e.loaded/e.total*100)}%`)});emulator.add_listener('emulator-ready',()=>onStatus?.(`Ready · ${name} · click display for keyboard and mouse`));emulator.add_listener('emulator-started',()=>onStatus?.(`Running locally in v86 · ${name}`));emulator.add_listener('emulator-stopped',()=>onStatus?.('Web VM stopped'));emulator.add_listener('serial0-output-byte',b=>{serialText+=String.fromCharCode(b&255);onSerial?.(serialText)});return{name};}
export async function stopBrowserVm(){if(!emulator)return;try{emulator.stop()}catch{}try{await emulator.destroy?.()}catch{}emulator=null;}
export function sendBrowserSerial(text){if(!emulator)throw new Error('Start the Web VM first.');emulator.serial0_send(text);}
